package com.itpay.mp.user.dto;

import com.itpay.core.base.dto.UuidBaseDto;

import java.util.Date;

public class MpRolePermissionRef extends UuidBaseDto {
    private static final long serialVersionUID = -4941418916937305027L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mp_role_permission_ref.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mp_role_permission_ref.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mp_role_permission_ref.permission_id
     *
     * @mbg.generated
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mp_role_permission_ref.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mp_role_permission_ref.id
     *
     * @return the value of tb_mp_role_permission_ref.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mp_role_permission_ref.id
     *
     * @param id the value for tb_mp_role_permission_ref.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mp_role_permission_ref.role_id
     *
     * @return the value of tb_mp_role_permission_ref.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mp_role_permission_ref.role_id
     *
     * @param roleId the value for tb_mp_role_permission_ref.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mp_role_permission_ref.permission_id
     *
     * @return the value of tb_mp_role_permission_ref.permission_id
     *
     * @mbg.generated
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mp_role_permission_ref.permission_id
     *
     * @param permissionId the value for tb_mp_role_permission_ref.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mp_role_permission_ref.create_time
     *
     * @return the value of tb_mp_role_permission_ref.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mp_role_permission_ref.create_time
     *
     * @param createTime the value for tb_mp_role_permission_ref.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}