package com.itpay.mp.user.dto;

import com.itpay.core.base.dto.UuidBaseDto;

import java.util.Date;

public class MpUseRoleRef extends UuidBaseDto {
    private static final long serialVersionUID = -2720073215998096846L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_user_role_ref.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_user_role_ref.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_user_role_ref.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mp_user_role_ref.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_user_role_ref.id
     *
     * @return the value of t_mp_user_role_ref.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_user_role_ref.id
     *
     * @param id the value for t_mp_user_role_ref.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_user_role_ref.role_id
     *
     * @return the value of t_mp_user_role_ref.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_user_role_ref.role_id
     *
     * @param roleId the value for t_mp_user_role_ref.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_user_role_ref.user_id
     *
     * @return the value of t_mp_user_role_ref.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_user_role_ref.user_id
     *
     * @param userId the value for t_mp_user_role_ref.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mp_user_role_ref.create_time
     *
     * @return the value of t_mp_user_role_ref.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mp_user_role_ref.create_time
     *
     * @param createTime the value for t_mp_user_role_ref.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}