package com.itpay.mp.user.dto;

import java.io.Serializable;
import java.util.Date;

public class UserDto implements Serializable{
    private static final long serialVersionUID = -2172611121783144604L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.id
     *
     *  
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.email
     *
     *  
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.status
     *
     *  
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.name
     *
     *  
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.sex
     *
     *  
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.create_time
     *
     *  
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.phone
     *
     *  
     */
    private String  phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.id
     *
     * @return the value of T_USER_INFO.id
     *
     *  
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.id
     *
     * @param id the value for T_USER_INFO.id
     *
     *  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.email
     *
     * @return the value of T_USER_INFO.email
     *
     *  
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.email
     *
     * @param email the value for T_USER_INFO.email
     *
     *  
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.status
     *
     * @return the value of T_USER_INFO.status
     *
     *  
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.status
     *
     * @param status the value for T_USER_INFO.status
     *
     *  
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.name
     *
     * @return the value of T_USER_INFO.name
     *
     *  
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.name
     *
     * @param name the value for T_USER_INFO.name
     *
     *  
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.sex
     *
     * @return the value of T_USER_INFO.sex
     *
     *  
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.sex
     *
     * @param sex the value for T_USER_INFO.sex
     *
     *  
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.create_time
     *
     * @return the value of T_USER_INFO.create_time
     *
     *  
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.create_time
     *
     * @param createTime the value for T_USER_INFO.create_time
     *
     *  
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.phone
     *
     * @return the value of T_USER_INFO.phone
     *
     *  
     */
    public String  getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.phone
     *
     * @param phone the value for T_USER_INFO.phone
     *
     *  
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}