package com.itpay.mp.user.dto;

import com.itpay.base.enums.ESexType;
import com.itpay.base.enums.EUserStatus;
import com.itpay.core.base.dto.UuidBaseDto;

import java.util.Date;
/**
 * @author lfeng1
 */
public class UserDto extends UuidBaseDto {
    private static final long serialVersionUID = -2172611121783144604L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.id
     *
     *  
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.email
     *
     *  
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.status
     *
     *  
     */
    private EUserStatus status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.name
     *
     *  
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.sex
     *
     *  
     */
    private ESexType sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.create_time
     *
     *  
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.phone
     *
     *  
     */
    private String  phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.id
     *
     * @return the value of T_USER_INFO.id
     *
     *  
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.id
     *
     * @param id the value for T_USER_INFO.id
     *
     *  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.email
     *
     * @return the value of T_USER_INFO.email
     *
     *  
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.email
     *
     * @param email the value for T_USER_INFO.email
     *
     *  
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }


    public EUserStatus getStatus() {
        return status;
    }

    public void setStatus(EUserStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.name
     *
     * @return the value of T_USER_INFO.name
     *
     *  
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.name
     *
     * @param name the value for T_USER_INFO.name
     *
     *  
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }


    public ESexType getSex() {
        return sex;
    }

    public void setSex(ESexType sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.create_time
     *
     * @return the value of T_USER_INFO.create_time
     *
     *  
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.create_time
     *
     * @param createTime the value for T_USER_INFO.create_time
     *
     *  
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.phone
     *
     * @return the value of T_USER_INFO.phone
     *
     *  
     */
    public String  getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.phone
     *
     * @param phone the value for T_USER_INFO.phone
     *
     *  
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}