package com.itpay.mp.user.dao;


import com.itpay.mp.user.dto.MpUseRoleRef;
import org.springframework.stereotype.Repository;

@Repository("mpUseRoleRefMapper")
public interface MpUseRoleRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    int insert(MpUseRoleRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    int insertSelective(MpUseRoleRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    MpUseRoleRef selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MpUseRoleRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mp_user_role_ref
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MpUseRoleRef record);
}