package com.itpay.mp.user.dao;


import com.itpay.mp.user.dto.UserLoginDto;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository("userLoginDtoMapper")
public interface UserLoginDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    int insert(UserLoginDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    int insertSelective(UserLoginDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    UserLoginDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    int updateByPrimaryKeySelective(UserLoginDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     *  
     */
    int updateByPrimaryKey(UserLoginDto record);

    /**
     * 根据用户登陆名称查询出用户信息
     *
     * @param loginName 登陆名称
     * @return UserLoginDto
     */
    
    UserLoginDto findByUserLoginName(@Param("loginName") String loginName);


    /**
     * 根据用户id查询登陆用户信息
     *
     * @param userId 用户的id
     * @return List<UserLoginDto>
     */
    List<UserLoginDto> findByUserId(@Param("userId")String userId);

    /**
     * 根据参数进行查询
     * @param queryParam 查询参数
     * @return
     */
    List<UserLoginDto> findBySearch(UserLoginDto queryParam);


    /**
     * 批量插入
     * @param records
     * @return
     */
    int insertBatch(@Param("records") List<UserLoginDto> records);


}