package com.itpay.mp.user.dao;


import com.itpay.mp.user.dto.UserDto;
import org.springframework.stereotype.Repository;

@Repository("userMapper")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    UserDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    int updateByPrimaryKeySelective(UserDto record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     *  
     */
    int updateByPrimaryKey(UserDto record);
    
}